# Generated by Django 5.0.2 on 2024-05-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('auther', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
            ],
        ),
    ]
