# Generated by Django 5.0.2 on 2024-05-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='auther',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='isbn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
